DROP TABLE T_USUARIO PURGE;
DROP TABLE T_CONTRATO_ADENDA PURGE;
DROP TABLE T_CONTRATO_ANEXO PURGE;
DROP TABLE T_CONTRATO_VALORIZACION PURGE;
DROP TABLE T_EMPRESA_SUPERVISORA PURGE;
DROP TABLE T_ROL_OPCIONES PURGE;
DROP TABLE T_TIPO_CAMBIO PURGE;
DROP TABLE T_CONCEPTO_INVERSION PURGE;
DROP TABLE T_CONCEPTO_VALORIZACION PURGE;
DROP TABLE T_CONTRATO PURGE;
DROP TABLE T_INFRAESTRUCTURA_TIPO_PLANTIL PURGE;
DROP TABLE T_INVERSION_TIPO PURGE;
DROP TABLE T_MEN PURGE;
DROP TABLE T_MODALIDAD_CONCESION PURGE;
DROP TABLE T_MONEDA PURGE;
DROP TABLE T_ROL PURGE;
DROP TABLE T_INFRAESTRUCTURA_TIPO PURGE;
DROP TABLE T_CONCESIONARIO PURGE;
DROP TABLE T_CARGO PURGE;
DROP TABLE T_TIPO_DOCUMENTO PURGE;
DROP TABLE T_EXP_RECONOCIMIENTO_DETALLE PURGE;
DROP TABLE T_EXP_RECONOCIMIENTO PURGE;
DROP TABLE T_IMPUESTO PURGE;
DROP TABLE T_INVERSION PURGE;
DROP TABLE T_INVERSION_TIPO_DESCRIPCION PURGE;
DROP TABLE T_UNIVERSO_TEMAS_CONTRATO PURGE;
DROP TABLE T_CONCESION PURGE;
DROP TABLE T_INFRAESTRUCTURA PURGE;

CREATE TABLE T_CARGO
(
	CRG_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	CRG_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	CRG_ID		  NUMBER  NOT NULL ,
	CRG_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	CRG_FECHA_ALTA	  DATE  NULL ,
	CRG_FECHA_CAMBIO  DATE  NULL ,
	CRG_FECHA_BAJA	  DATE  NULL ,
	CRG_TERMINAL	  VARCHAR2(20)  NULL ,
	CRG_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	CRG_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	CRG_USUARIO_BAJA  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKCARGO ON T_CARGO
(CRG_ID  ASC);



ALTER TABLE T_CARGO
	ADD CONSTRAINT  XPKCARGO PRIMARY KEY (CRG_ID);



CREATE TABLE T_CONCEPTO_INVERSION
(
	CNV_NOMBRE	  VARCHAR2(50)  NOT NULL ,
	CNV_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	CNV_ID		  NUMBER  NOT NULL ,
	CNV_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	CNV_FECHA_ALTA	  DATE  NULL ,
	CNV_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	CNV_FECHA_CAMBIO  DATE  NULL ,
	CNV_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	CNV_FECHA_BAJA	  DATE  NULL ,
	CNV_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	CNV_TERMINAL	  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKCONCEPTOS_DE_INVERSIÓN ON T_CONCEPTO_INVERSION
(CNV_ID  ASC);



ALTER TABLE T_CONCEPTO_INVERSION
	ADD CONSTRAINT  XPKCONCEPTOS_DE_INVERSIÓN PRIMARY KEY (CNV_ID);



CREATE TABLE T_CONCEPTO_VALORIZACION
(
	CVA_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	CVA_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	CVA_ID		  NUMBER  NOT NULL ,
	CVA_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	CVA_FECHA_ALTA	  DATE  NULL ,
	CVA_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	CVA_FECHA_CAMBIO  DATE  NULL ,
	CVA_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	CVA_FECHA_BAJA	  DATE  NULL ,
	CVA_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	CVA_TERMINAL	  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKCONCEPTO_DE_VALORIZACIÓN ON T_CONCEPTO_VALORIZACION
(CVA_ID  ASC);



ALTER TABLE T_CONCEPTO_VALORIZACION
	ADD CONSTRAINT  XPKCONCEPTO_DE_VALORIZACIÓN PRIMARY KEY (CVA_ID);



CREATE TABLE T_CONCESIONARIO
(
	CNC_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	CNC_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	CNC_ID		  NUMBER  NOT NULL ,
	CNC_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	CNC_FECHA_ALTA	  DATE  NULL ,
	CNC_FECHA_CAMBIO  DATE  NULL ,
	CNC_FECHA_BAJA	  DATE  NULL ,
	CNC_TERMINAL	  VARCHAR2(20)  NULL ,
	CNC_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	CNC_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	CNC_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	CNC_TELEFONO	  VARCHAR2(15)  NULL ,
	CNC_NRO_DOCUMENTO  VARCHAR2(20)  NULL ,
	CNC_DIRECCION	  VARCHAR2(20)  NULL ,
	CNC_CORREO	  VARCHAR2(20)  NULL ,
	CNC_REPRESENTANTE_LEGAL  VARCHAR2(20)  NULL ,
	CRG_ID		  NUMBER  NULL ,
	TDO_ID		  NUMBER  NULL 
);



CREATE UNIQUE INDEX XPKCONCESIONARIO ON T_CONCESIONARIO
(CNC_ID  ASC);



ALTER TABLE T_CONCESIONARIO
	ADD CONSTRAINT  XPKCONCESIONARIO PRIMARY KEY (CNC_ID);



CREATE TABLE T_CONTRATO
(
	CON_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	CON_FECHA_ALTA	  DATE  NULL ,
	CON_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	CON_FECHA_CAMBIO  DATE  NULL ,
	CON_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	CON_FECHA_BAJA	  DATE  NULL ,
	CON_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	CON_TERMINAL	  VARCHAR2(20)  NULL ,
	MCO_ID		  NUMBER  NOT NULL ,
	CNC_ID		  NUMBER  NULL ,
	TIV_ID		  NUMBER  NULL ,
	CON_ID		  NUMBER  NOT NULL ,
	TIN_ID		  NUMBER  NOT NULL ,
	MON_ID		  NUMBER  NULL ,
	TOTAL_DE_LA_VALORIZACIÓN  NUMBER  NULL ,
	CON_CONCESION	  VARCHAR2(4000)  NOT NULL 
);



CREATE UNIQUE INDEX XPKCONTRATO ON T_CONTRATO
(CON_ID  ASC,TIN_ID  ASC);



ALTER TABLE T_CONTRATO
	ADD CONSTRAINT  XPKCONTRATO PRIMARY KEY (CON_ID,TIN_ID);



CREATE TABLE T_CONTRATO_ADENDA
(
	CAD_ID		  NUMBER  NOT NULL ,
	CAD_FECHA	  DATE  NULL ,
	CAD_DOCUMENTO_FISICO  VARCHAR2(255)  NULL ,
	TIN_ID		  NUMBER  NOT NULL ,
	CON_ID		  NUMBER  NOT NULL 
);



CREATE UNIQUE INDEX XPKCONTRATO_ADENDA ON T_CONTRATO_ADENDA
(CAD_ID  ASC,TIN_ID  ASC,CON_ID  ASC);



ALTER TABLE T_CONTRATO_ADENDA
	ADD CONSTRAINT  XPKCONTRATO_ADENDA PRIMARY KEY (CAD_ID,TIN_ID,CON_ID);



CREATE TABLE T_CONTRATO_ANEXO
(
	CAX_ID		  NUMBER  NOT NULL ,
	CAX_FECHA	  DATE  NULL ,
	CAX_DOCUMENTO_FISICO  VARCHAR2(255)  NULL ,
	TIN_ID		  NUMBER  NOT NULL ,
	CON_ID		  NUMBER  NOT NULL 
);



CREATE UNIQUE INDEX XPKCONTRATO_ANEXO ON T_CONTRATO_ANEXO
(CAX_ID  ASC,TIN_ID  ASC,CON_ID  ASC);



ALTER TABLE T_CONTRATO_ANEXO
	ADD CONSTRAINT  XPKCONTRATO_ANEXO PRIMARY KEY (CAX_ID,TIN_ID,CON_ID);



CREATE TABLE T_CONTRATO_DETALLE
(
	CND_CORRELATIVO	  NUMBER  NOT NULL ,
	CND_VALOR_TEXTO	  VARCHAR2(200),
	CND_VALOR_FECHA	  DATE  NULL ,
	CND_VALOR_NUMERICO  NUMBER(14,3)  NULL ,
	CND_REFERENCIA	  VARCHAR2(4000)  NOT NULL ,
	CON_ID		  NUMBER  NOT NULL ,
	TIN_ID		  NUMBER  NOT NULL ,
	UTC_ID		  NUMBER  NOT NULL 
);



CREATE UNIQUE INDEX XPKCONTRATO_DETALLE ON T_CONTRATO_DETALLE
(CON_ID  ASC,TIN_ID  ASC,CND_CORRELATIVO  ASC,UTC_ID  ASC);



ALTER TABLE T_CONTRATO_DETALLE
	ADD CONSTRAINT  XPKCONTRATO_DETALLE PRIMARY KEY (CON_ID,TIN_ID,CND_CORRELATIVO,UTC_ID);



CREATE TABLE T_CONTRATO_VALORIZACION
(
	CVL_FECHA	  DATE  NULL ,
	CVL_ID		  NUMBER  NOT NULL ,
	CVA_ID		  NUMBER  NULL ,
	ALCANCE		  VARCHAR2(20)  NULL ,
	CVA_MONTO	  NUMBER(14,2)   DEFAULT  0 NOT NULL ,
	FECHA_INICIO	  DATE  NULL ,
	DURACIÓN	  NUMBER   DEFAULT  0 NULL ,
	TIN_ID		  NUMBER  NOT NULL ,
	CON_ID		  NUMBER  NOT NULL 
);



CREATE UNIQUE INDEX XPKCONTRATO_ETAPA ON T_CONTRATO_VALORIZACION
(CVL_ID  ASC,TIN_ID  ASC,CON_ID  ASC);



ALTER TABLE T_CONTRATO_VALORIZACION
	ADD CONSTRAINT  XPKCONTRATO_ETAPA PRIMARY KEY (CVL_ID,TIN_ID,CON_ID);



CREATE TABLE T_EMPRESA_SUPERVISORA
(
	SUP_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	SUP_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	SUP_ID		  NUMBER  NOT NULL ,
	SUP_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	SUP_FECHA_ALTA	  DATE  NULL ,
	SUP_FECHA_CAMBIO  DATE  NULL ,
	SUP_FECHA_BAJA	  DATE  NULL ,
	SUP_TERMINAL	  VARCHAR2(20)  NULL ,
	SUP_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	SUP_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	SUP_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	SUP_TELEFONO	  VARCHAR2(15)  NULL ,
	SUP_NRO_DOCUMENTO  VARCHAR2(20)  NULL ,
	SUP_DIRECCION	  VARCHAR2(20)  NULL ,
	SUP_CORREO	  VARCHAR2(20)  NULL ,
	SUP_REPRESENTANTE_LEGAL  VARCHAR2(20)  NULL ,
	CRG_ID		  NUMBER  NULL ,
	TDO_ID		  NUMBER  NULL 
);



CREATE UNIQUE INDEX XPKEMPRESA_SUPERVISORA ON T_EMPRESA_SUPERVISORA
(SUP_ID  ASC);



ALTER TABLE T_EMPRESA_SUPERVISORA
	ADD CONSTRAINT  XPKEMPRESA_SUPERVISORA PRIMARY KEY (SUP_ID);



CREATE TABLE T_EXP_RECONOCIMIENTO
(
	ERC_STD		  VARCHAR2(20)  NOT NULL ,
	ERC_CONCEPTO	  NUMBER(14,2)  NULL ,
	ERC_VALOR_TOTAL_EXPEDIENTE  NUMBER(14,2)  NULL ,
	ERC_VALOR_BRUTO	  NUMBER(14,2)  NULL ,
	ERC_PORCENTAJE_AMORTIZACION  NUMBER(14,2)  NULL ,
	ERC_VALOR_IGV	  NUMBER(14,2)  NULL ,
	ERC_VALOR_TOTAL	  NUMBER(14,2)  NULL ,
	MON_ID		  NUMBER  NULL ,
	ERC_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	ERC_FECHA_ALTA	  DATE  NULL ,
	ERC_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	ERC_FECHA_CAMBIO  DATE  NULL ,
	ERC_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	ERC_FECHA_BAJA	  DATE  NULL ,
	ERC_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	ERC_TERMINAL	  VARCHAR2(20)  NULL ,
	IMP_ID		  NUMBER  NULL ,
	IGV		  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKEXPEDIENTE_DE_RECONOCIMIENT ON T_EXP_RECONOCIMIENTO
(ERC_STD  ASC);



ALTER TABLE T_EXP_RECONOCIMIENTO
	ADD CONSTRAINT  XPKEXPEDIENTE_DE_RECONOCIMIENT PRIMARY KEY (ERC_STD);



CREATE TABLE T_EXP_RECONOCIMIENTO_DETALLE
(
	ERD_VALOR_TOTAL	  NUMERIC(14,2)  NOT NULL ,
	CNV_ID		  NUMBER  NULL ,
	MON_ID		  NUMBER  NULL ,
	ERD_ID		  NUMBER  NOT NULL ,
	ERC_STD		  VARCHAR2(20)  NOT NULL 
);



CREATE UNIQUE INDEX XPKEXPEDIENTE_DE_RECONOCIMIENT ON T_EXP_RECONOCIMIENTO_DETALLE
(ERD_ID  ASC,ERC_STD  ASC);



ALTER TABLE T_EXP_RECONOCIMIENTO_DETALLE
	ADD CONSTRAINT  XPKEXPEDIENTE_DE_RECONOCIMIENT PRIMARY KEY (ERD_ID,ERC_STD);



CREATE TABLE T_IMPUESTO
(
	IMP_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	IMP_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	IMP_ID		  NUMBER  NOT NULL ,
	IMP_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	IMP_FECHA_ALTA	  DATE  NULL ,
	IMP_FECHA_CAMBIO  DATE  NULL ,
	IMP_FECHA_BAJA	  DATE  NULL ,
	IMP_TERMINAL	  VARCHAR2(20)  NULL ,
	IMP_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	IMP_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	IMP_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	IMP_PORCENTAJE	  NUMBER(14,2)  NOT NULL 
);



CREATE UNIQUE INDEX XPKIMPUESTO ON T_IMPUESTO
(IMP_ID  ASC);



ALTER TABLE T_IMPUESTO
	ADD CONSTRAINT  XPKIMPUESTO PRIMARY KEY (IMP_ID);



CREATE TABLE T_INFRAESTRUCTURA_TIPO
(
	TIN_NOMBRE	  VARCHAR2(50)  NOT NULL ,
	TIN_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	TIN_ID		  NUMBER  NOT NULL ,
	TIN_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	TIN_FECHA_ALTA	  DATE  NULL ,
	TIN_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	TIN_FECHA_CAMBIO  DATE  NULL ,
	TIN_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	TIN_FECHA_BAJA	  DATE  NULL ,
	TIN_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	TIN_TERMINAL	  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKINFRAESTRUCTURA_TIPO ON T_INFRAESTRUCTURA_TIPO
(TIN_ID  ASC);



ALTER TABLE T_INFRAESTRUCTURA_TIPO
	ADD CONSTRAINT  XPKINFRAESTRUCTURA_TIPO PRIMARY KEY (TIN_ID);



CREATE TABLE T_INFRAESTRUCTURA_TIPO_PLANTIL
(
	TIN_ID		  NUMBER  NOT NULL ,
	UTC_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	UTC_FECHA_ALTA	  DATE  NULL ,
	UTC_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	UTC_FECHA_CAMBIO  DATE  NULL ,
	UTC_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	UTC_FECHA_BAJA	  DATE  NULL ,
	UTC_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	UTC_TERMINAL	  VARCHAR2(20)  NULL ,
	UTC_ID		  NUMBER  NOT NULL 
);



CREATE UNIQUE INDEX XPKINFRAESTRUCTURA_TIPO_DE_PLA ON T_INFRAESTRUCTURA_TIPO_PLANTIL
(TIN_ID  ASC,UTC_ID  ASC);



ALTER TABLE T_INFRAESTRUCTURA_TIPO_PLANTIL
	ADD CONSTRAINT  XPKINFRAESTRUCTURA_TIPO_DE_PLA PRIMARY KEY (TIN_ID,UTC_ID);



CREATE TABLE T_INVERSION
(
	INV_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	INV_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	INV_ID		  NUMBER  NOT NULL ,
	INV_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	INV_FECHA_ALTA	  DATE  NULL ,
	INV_FECHA_CAMBIO  DATE  NULL ,
	INV_FECHA_BAJA	  DATE  NULL ,
	INV_TERMINAL	  VARCHAR2(20)  NULL ,
	TIV_ID		  NUMBER  NULL ,
	INV_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	INV_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	INV_USUARIO_BAJA  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKINVERSION ON T_INVERSION
(INV_ID  ASC);



ALTER TABLE T_INVERSION
	ADD CONSTRAINT  XPKINVERSION PRIMARY KEY (INV_ID);



CREATE TABLE T_INVERSION_TIPO
(
	TIV_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	TIV_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	TIV_ID		  NUMBER  NOT NULL ,
	TIV_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	TIV_FECHA_ALTA	  DATE  NULL ,
	TIV_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	TIV_FECHA_CAMBIO  DATE  NULL ,
	TIV_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	TIV_FECHA_BAJA	  DATE  NULL ,
	TIV_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	TIV_TERMINAL	  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKINVERSION_TIPO ON T_INVERSION_TIPO
(TIV_ID  ASC);



ALTER TABLE T_INVERSION_TIPO
	ADD CONSTRAINT  XPKINVERSION_TIPO PRIMARY KEY (TIV_ID);



CREATE TABLE T_INVERSION_TIPO_DESCRIPCION
(
	ITD_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	ITD_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	ITD_ID		  NUMBER  NOT NULL ,
	ITD_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	ITD_FECHA_ALTA	  DATE  NULL ,
	ITD_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	ITD_FECHA_CAMBIO  DATE  NULL ,
	ITD_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	ITD_FECHA_BAJA	  DATE  NULL ,
	ITD_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	ITD_TERMINAL	  VARCHAR2(20)  NULL ,
	TIV_ID		  NUMBER  NOT NULL 
);



CREATE UNIQUE INDEX XPKINVERSION_TIPO_DESCRIPCION ON T_INVERSION_TIPO_DESCRIPCION
(ITD_ID  ASC,TIV_ID  ASC);



ALTER TABLE T_INVERSION_TIPO_DESCRIPCION
	ADD CONSTRAINT  XPKINVERSION_TIPO_DESCRIPCION PRIMARY KEY (ITD_ID,TIV_ID);



CREATE TABLE T_MEN
(
	MEN_ID		  NUMBER  NOT NULL ,
	MEN_NOMBRE	  VARCHAR2(4000)  NOT NULL ,
	MEN_FORMULARIO	  VARCHAR2(4000)  NOT NULL ,
	MEN_PADRE	  NUMBER  NULL ,
	MEN_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	MEN_FECHA_ALTA	  DATE  NULL ,
	MEN_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	MEN_FECHA_CAMBIO  DATE  NULL ,
	MEN_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	MEN_FECHA_BAJA	  DATE  NULL ,
	MEN_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	MEN_TERMINAL	  VARCHAR2(20)  NULL ,
	DESCRIPCION	  VARCHAR2(4000)  NOT NULL 
);



CREATE UNIQUE INDEX XPKOPCIONES_DE_LA_APLICACIÓN ON T_MEN
(MEN_ID  ASC);



ALTER TABLE T_MEN
	ADD CONSTRAINT  XPKOPCIONES_DE_LA_APLICACIÓN PRIMARY KEY (MEN_ID);



CREATE TABLE T_MODALIDAD_CONCESION
(
	MCO_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	MCO_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	MCO_ID		  NUMBER  NOT NULL ,
	MCO_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	MCO_FECHA_ALTA	  DATE  NULL ,
	MCO_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	MCO_FECHA_CAMBIO  DATE  NULL ,
	MCO_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	MCO_FECHA_BAJA	  DATE  NULL ,
	MCO_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	MCO_TERMINAL	  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKMODALIDAD_DE_CONCESIÓN ON T_MODALIDAD_CONCESION
(MCO_ID  ASC);



ALTER TABLE T_MODALIDAD_CONCESION
	ADD CONSTRAINT  XPKMODALIDAD_DE_CONCESIÓN PRIMARY KEY (MCO_ID);



CREATE TABLE T_MONEDA
(
	MON_NOMBRE	  VARCHAR2(50)  NOT NULL ,
	MON_ID		  NUMBER  NOT NULL ,
	MON_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	MON_FECHA_ALTA	  DATE  NULL ,
	MON_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	MON_FECHA_CAMBIO  DATE  NULL ,
	MON_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	MON_FECHA_BAJA	  DATE  NULL ,
	MON_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	MON_TERMINAL	  VARCHAR2(20)  NULL ,
	MON_SIMBOLO	  VARCHAR2(3)  NULL 
);



CREATE UNIQUE INDEX XPKMONEDA ON T_MONEDA
(MON_ID  ASC);



ALTER TABLE T_MONEDA
	ADD CONSTRAINT  XPKMONEDA PRIMARY KEY (MON_ID);



CREATE TABLE T_ROL
(
	ROL_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	ROL_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	ROL_ID		  NUMBER  NOT NULL ,
	ROL_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	ROL_FECHA_ALTA	  DATE  NULL ,
	ROL_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	ROL_FECHA_CAMBIO  DATE  NULL ,
	ROL_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	ROL_FECHA_BAJA	  DATE  NULL ,
	ROL_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	ROL_TERMINAL	  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKROL ON T_ROL
(ROL_ID  ASC);



ALTER TABLE T_ROL
	ADD CONSTRAINT  XPKROL PRIMARY KEY (ROL_ID);



CREATE TABLE T_ROL_OPCIONES
(
	MEN_ID		  NUMBER  NOT NULL ,
	ROL_ID		  NUMBER  NOT NULL ,
	TRO_CONSULTAR	  NUMBER   DEFAULT  0 NOT NULL ,
	TRO_AGREGAR	  NUMBER   DEFAULT  0 NOT NULL ,
	TRO_MODIFICAR	  NUMBER   DEFAULT  0 NOT NULL ,
	TRO_ELIMINAR	  NUMBER   DEFAULT  0 NOT NULL ,
	TRO_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	TRO_FECHA_ALTA	  DATE  NULL ,
	TRO_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	TRO_FECHA_CAMBIO  DATE  NULL ,
	TRO_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	TRO_FECHA_BAJA	  DATE  NULL ,
	TRO_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	TRO_TERMINAL	  VARCHAR2(20)  NULL ,
	RXO_ID		  NUMBER  NOT NULL 
);



CREATE UNIQUE INDEX XPKOPCIONES_POR_ROL ON T_ROL_OPCIONES
(RXO_ID  ASC);



ALTER TABLE T_ROL_OPCIONES
	ADD CONSTRAINT  XPKOPCIONES_POR_ROL PRIMARY KEY (RXO_ID);



CREATE TABLE T_TIPO_CAMBIO
(
	TDC_IMPORTE_VENTA  NUMBER(14,3)   DEFAULT  1 NOT NULL ,
	TDC_IMPORTE_COMPRA  NUMBER(14,3)   DEFAULT  1 NULL ,
	TDC_FECHA	  DATE  NOT NULL ,
	MON_ID		  NUMBER  NOT NULL ,
	TDC_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	TDC_FECHA_ALTA	  DATE  NULL ,
	TDC_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	TDC_FECHA_CAMBIO  DATE  NULL ,
	TDC_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	TDC_FECHA_BAJA	  DATE  NULL ,
	TDC_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	TDC_TERMINAL	  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKTIPO_DE_CAMBIO ON T_TIPO_CAMBIO
(TDC_FECHA  ASC,MON_ID  ASC);



ALTER TABLE T_TIPO_CAMBIO
	ADD CONSTRAINT  XPKTIPO_DE_CAMBIO PRIMARY KEY (TDC_FECHA,MON_ID);



CREATE TABLE T_TIPO_DOCUMENTO
(
	TDO_NOMBRE	  VARCHAR2(100)  NOT NULL ,
	TDO_DESCRIPCION	  VARCHAR2(100)  NOT NULL ,
	TDO_ID		  NUMBER  NOT NULL ,
	TDO_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	TDO_FECHA_ALTA	  DATE  NULL ,
	TDO_FECHA_CAMBIO  DATE  NULL ,
	TDO_FECHA_BAJA	  DATE  NULL ,
	TDO_TERMINAL	  VARCHAR2(20)  NULL ,
	TDO_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	TDO_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	TDO_USUARIO_BAJA  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKTIPO_DE_DOCUMENTO ON T_TIPO_DOCUMENTO
(TDO_ID  ASC);



ALTER TABLE T_TIPO_DOCUMENTO
	ADD CONSTRAINT  XPKTIPO_DE_DOCUMENTO PRIMARY KEY (TDO_ID);


CREATE TABLE T_UNIVERSO_TEMAS_CONTRATO
(
	UTC_ID		  NUMBER  NOT NULL ,
	UTC_NOMBRE	  VARCHAR2(50)  NOT NULL ,
	UTC_DESCRIPCION	  VARCHAR2(4000)  NOT NULL ,
	UTC_TIPO_DATO	  VARCHAR2(1) NOT NULL,
	UTC_TODASLASINFRAESTRUCTURAS  NUMBER   DEFAULT  1 NOT NULL ,
	UTC_ESTADO	  NUMBER   DEFAULT  0 NOT NULL ,
	UTC_FECHA_ALTA	  DATE  NULL ,
	UTC_USUARIO_ALTA  VARCHAR2(20)  NULL ,
	UTC_FECHA_CAMBIO  DATE  NULL ,
	UTC_USUARIO_CAMBIO  VARCHAR2(20)  NULL ,
	UTC_FECHA_BAJA	  DATE  NULL ,
	UTC_USUARIO_BAJA  VARCHAR2(20)  NULL ,
	UTC_TERMINAL	  VARCHAR2(20)  NULL 
);



CREATE UNIQUE INDEX XPKUNIVERSO_TEMAS_CONTRATO ON T_UNIVERSO_TEMAS_CONTRATO
(UTC_ID  ASC);



ALTER TABLE T_UNIVERSO_TEMAS_CONTRATO
	ADD CONSTRAINT  XPKUNIVERSO_TEMAS_CONTRATO PRIMARY KEY (UTC_ID);



CREATE TABLE T_USUARIO 
(
  USU_ID NUMBER NOT NULL 
, USU_NOMBRE VARCHAR2(100 BYTE) NOT NULL 
, USU_ESTADO NUMBER DEFAULT 0 NOT NULL 
, USU_FECHA_ALTA DATE 
, USU_USUARIO_ALTA VARCHAR2(20 BYTE) 
, USU_FECHA_CAMBIO DATE 
, USU_USUARIO_CAMBIO VARCHAR2(20 BYTE) 
, USU_FECHA_BAJA DATE 
, USU_USUARIO_BAJA VARCHAR2(20 BYTE) 
, USU_TERMINAL VARCHAR2(20 BYTE) 
, USU_ESEXTERNO NUMBER DEFAULT 0 NOT NULL 
, ROL_ID NUMBER NOT NULL 
, USU_CONTRASENYA VARCHAR2(20 BYTE) NOT NULL 
, CRG_ID NUMBER 
, USU_USUARIO VARCHAR2(20 BYTE) NOT NULL 
);

CREATE UNIQUE INDEX USUARIO_UK ON T_USUARIO (USU_ID ASC);

ALTER TABLE T_USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY (USU_ID) USING INDEX USUARIO_UK ENABLE;


--TABLA INFRAESTRUCTURA
CREATE TABLE "OSITRAN"."T_INFRAESTRUCTURA" 
   (	"INF_ID" NUMBER, 
	"INF_NOMBRE" VARCHAR2(100 BYTE), 
	"CSI_ID" NUMBER, 
        "INF_ESTADO" NUMBER,
	"INF_FECHA_ALTA" DATE, 
	"INF_USUARIO_ALTA" VARCHAR2(50 BYTE), 
	"INF_FECHA_CAMBIO" DATE, 
	"INF_USUARIO_CAMBIO" VARCHAR2(50 BYTE), 
	"INF_FECHA_BAJA" DATE, 
	"INF_USUARIO_BAJA" VARCHAR2(50 BYTE), 
	"INF_TERMINAL" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("INF_ID"), 
	 CONSTRAINT "FK_T_CONCESION" FOREIGN KEY ("CSI_ID")
	 REFERENCES "OSITRAN"."T_CONCESION" ("CSI_ID") ENABLE
   ) ;
--SECUENCIA DE LA TABLA INFRAESTRUCTURA
CREATE SEQUENCE SEQ_INFRAESTRUCTURA;

--TABLA INFRAESTRUCTURA TIPO
CREATE TABLE "OSITRAN"."T_INFRAESTRUCTURA_TIPO" 
   (	"TIN_NOMBRE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"TIN_DESCRIPCION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"TIN_ID" NUMBER NOT NULL ENABLE, 
	"TIN_ESTADO" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"TIN_FECHA_ALTA" DATE, 
	"TIN_USUARIO_ALTA" VARCHAR2(20 BYTE), 
	"TIN_FECHA_CAMBIO" DATE, 
	"TIN_USUARIO_CAMBIO" VARCHAR2(20 BYTE), 
	"TIN_FECHA_BAJA" DATE, 
	"TIN_USUARIO_BAJA" VARCHAR2(20 BYTE), 
	"TIN_TERMINAL" VARCHAR2(20 BYTE), 
        CONSTRAINT "PK_T_INFRAESTRUCTURA_TIPO" PRIMARY KEY ("TIN_ID")
 
   );
--SECUENCIA DE LA TABLA INFRAESTRUCTURA
CREATE SEQUENCE SEQ_INFRAESTRUCTURA_TIPO;


--TABLA CONCESION
CREATE TABLE "OSITRAN"."T_CONCESION" 
   (	"CSI_ID" NUMBER, 
	"TIN_ID" NUMBER, 
        "CSI_ESTADO" NUMBER,
        "CSI_NOMBRE" VARCHAR2(50 BYTE),
	"CSI_FECHA_ALTA" DATE, 
	"CSI_USUARIO_ALTA" VARCHAR2(50 BYTE), 
	"CSI_FECHA_CAMBIO" DATE, 
	"CSI_USUARIO_CAMBIO" VARCHAR2(50 BYTE), 
	"CSI_FECHA_BAJA" DATE, 
	"CSI_USUARIO_BAJA" VARCHAR2(50 BYTE), 
	"CSI_TERMINAL" VARCHAR2(50 BYTE), 
	
	 
        PRIMARY KEY ("CSI_ID"), 
        CONSTRAINT "FK_T_INFRAESTRUCTURA_TIPO" FOREIGN KEY ("TIN_ID")
        REFERENCES "OSITRAN"."T_INFRAESTRUCTURA_TIPO" ("TIN_ID") ENABLE
   ) ;

--SECUENCIA DE LA TABLA CONCESION
CREATE SEQUENCE SEQ_CONCESION;





CREATE TABLE T_IGV
   (	IGV_ID NUMBER NOT NULL ENABLE, 
	IGV_PORCENTAJE NUMBER(5,2) NOT NULL ENABLE, 
	IGV_FECHAVIGENCIA DATE, 
	IGV_FECHACADUCIDAD DATE, 
	IGV_ESTADO NUMBER, 
	IGV_FECHA_ALTA DATE, 
	IGV_USUARIO_ALTA VARCHAR2(50 BYTE), 
	IGV_FECHA_CAMBIO DATE, 
	IGV_USUARIO_CAMBIO VARCHAR2(50 BYTE), 
	IGV_FECHA_BAJA DATE, 
	IGV_USUARIO_BAJA VARCHAR2(50 BYTE), 
	IGV_TERMINAL VARCHAR2(20 BYTE),
        CONSTRAINT PK_T_IGV PRIMARY KEY (IGV_ID),
   );
   
CREATE SEQUENCE SEQ_IGV;
   





/*
SELECT COUNT(*) FROM T_USUARIO;

INSERT INTO "OSITRAN"."T_USUARIO" (USU_ID, USU_NOMBRE, USU_ESTADO, USU_USUARIO_ALTA, USU_USUARIO_CAMBIO, USU_USUARIO_BAJA, USU_TERMINAL, USU_ESEXTERNO, ROL_ID, 
USU_CONTRASENYA, CRG_ID) VALUES (1, '1', 1, '1', '1', '1', '1', 1, '1', '1', '1')

*/

